Metrics/LineLength:
  Max: 120

AllCops:
  Exclude:
    - 'spec/spec_helper.rb'
    - 'vendor/**/*'
    - 'lib/xing_api/version.rb'

Documentation:
  Enabled: false
FrozenStringLiteralComment:
  Enabled: false
